[versions]
about-libraries = "13.1.0" # https://github.com/mikepenz/AboutLibraries/releases
activity = "1.12.2" # https://developer.android.com/jetpack/androidx/releases/activity
appcompat = "1.7.1" # https://developer.android.com/jetpack/androidx/releases/appcompat
coil-compose = "3.3.0" # https://github.com/coil-kt/coil/blob/main/CHANGELOG.md
com-android-application = "9.0.0" # aka Android Gradle Plugin (AGP), https://developer.android.com/build/releases/gradle-plugin
compile-target-sdk = "36"
compose-bom = "+" # https://developer.android.com/jetpack/compose/bom/bom-mapping
constraintlayout = "+" # https://developer.android.com/jetpack/androidx/releases/constraintlayout
constraintlayout-compose = "+" # https://developer.android.com/jetpack/androidx/releases/constraintlayout
coordinatorlayout = "1.3.0" # https://developer.android.com/jetpack/androidx/releases/coordinatorlayout
coroutines = "1.10.2" # https://github.com/Kotlin/kotlinx.coroutines/releases
datastore = "1.2.0" # https://developer.android.com/jetpack/androidx/releases/datastore
firebase-bom = "+" # https://firebase.google.com/support/release-notes/android#compare-bom-versions
firebase-appdistribution-plugin = "5.2.0" # https://firebase.google.com/support/release-notes/android#latest_sdk_versions
firebase-crashlytics-plugin = "3.0.6" # https://firebase.google.com/support/release-notes/android#latest_sdk_versions
fragment = "1.8.9" # https://developer.android.com/jetpack/androidx/releases/fragment
google-services = "4.4.4" # https://developers.google.com/android/guides/releases
hilt = "2.58" # https://github.com/google/dagger/releases
hilt-androidx = "1.3.0" # https://developer.android.com/jetpack/androidx/releases/hilt
junit = "1.3.0" # https://developer.android.com/jetpack/androidx/releases/test
kotlin = "2.3.0" # https://kotlinlang.org/docs/releases.html
kotlinx-serialization = "+" # https://github.com/Kotlin/kotlinx.serialization/releases
ksp = "2.3.4" # https://github.com/google/ksp/releases
lifecycle = "2.10.0" # https://developer.android.com/jetpack/androidx/releases/lifecycle
media3 = "1.9.0" # https://developer.android.com/jetpack/androidx/releases/media3
min-sdk = "26" # https://developer.android.com/guide/topics/manifest/uses-sdk-element
navigation = "2.9.6" # https://developer.android.com/jetpack/androidx/releases/navigation
okhttp = "5.3.2" # https://square.github.io/okhttp/changelogs/changelog/
paging = "3.3.6" # https://developer.android.com/jetpack/androidx/releases/paging
protobuf = "0.9.6" # https://github.com/google/protobuf-gradle-plugin/releases
protoc = "4.33.2" # https://central.sonatype.com/artifact/com.google.protobuf/protobuf-kotlin-lite/versions
recyclerview = "+" # https://developer.android.com/jetpack/androidx/releases/recyclerview
retrofit = "3.0.0" # https://github.com/square/retrofit/releases/
robolectric = "4.16" # https://github.com/robolectric/robolectric/releases
room = "2.8.4" # https://developer.android.com/jetpack/androidx/releases/room
test-core-ktx = "1.7.0" # https://developer.android.com/jetpack/androidx/releases/test
test-rules = "1.7.0" # https://developer.android.com/jetpack/androidx/releases/test
test-runner = "1.7.0" # https://developer.android.com/jetpack/androidx/releases/test
viewpager2 = "1.1.0" # https://developer.android.com/jetpack/androidx/releases/viewpager2

[libraries]
about-libraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "about-libraries" }
about-libraries-compose = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "about-libraries" }
activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
animation = { group = "androidx.compose.animation", name = "animation" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil-compose" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout-compose" }
coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinatorlayout" }
datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" } # required for Crashlytics according to https://firebase.google.com/docs/crashlytics/get-started?platform=android#add-sdk
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-config = { group = "com.google.firebase", name = "firebase-config" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
foundation = { group = "androidx.compose.foundation", name = "foundation" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "fragment" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-compiler-androidx = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt-androidx" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-androidx" }
junit = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junit" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-protobuf = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }
lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
material3 = { group = "androidx.compose.material3", name = "material3" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }
navigation-safe-args-gradle-plugin = { group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" }
okhttp-urlconnection = { group = "com.squareup.okhttp3", name = "okhttp-urlconnection", version.ref = "okhttp" } # for CookieJar
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protoc" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protoc" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
retrofit-bom = { group = "com.squareup.retrofit2", name = "retrofit-bom", version.ref = "retrofit" }
retrofit-converter-kotlinx-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
rules = { group = "androidx.test", name = "rules", version.ref = "test-rules" }
runner = { group = "androidx.test", name = "runner", version.ref = "test-runner" }
test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "test-core-ktx" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }

[plugins]
about-libraries = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "about-libraries" }
com-android-application = { id = "com.android.application", version.ref = "com-android-application" } # aka Android Gradle Plugin (AGP), https://developer.android.com/build/releases/gradle-plugin#updating-plugin
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" } # https://developer.android.com/develop/ui/compose/compiler#version-catalog
firebase-appdistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebase-appdistribution-plugin" } # https://firebase.google.com/docs/app-distribution/android/distribute-gradle#step_1_set_up_your_android_project
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-plugin" } # https://firebase.google.com/docs/crashlytics/get-started?platform=android#add-plugin
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" } # https://firebase.google.com/docs/android/setup#add-config-file
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" } # https://developer.android.com/training/dependency-injection/hilt-android#setup
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" } # https://developer.android.com/build/migrate-to-ksp#add-ksp, https://kotlinlang.org/docs/ksp-quickstart.html#add-a-processor
protobuf = { id = "com.google.protobuf", version.ref = "protobuf" } # https://github.com/google/protobuf-gradle-plugin?tab=readme-ov-file#latest-version
