[versions]
activity = "1.9.1" # https://developer.android.com/jetpack/androidx/releases/activity
android-gradle-plugin = "8.5.1" # https://developer.android.com/build/releases/gradle-plugin
appcompat = "1.7.0" # https://developer.android.com/jetpack/androidx/releases/appcompat
coil-compose = "2.6.0" # https://github.com/coil-kt/coil/releases
compile-target-sdk = "34"
compose-bom = "2024.06.00" # https://developer.android.com/jetpack/compose/bom/bom-mapping
material3 = "1.3.0-beta05" # For using PullToRefreshBox added in 1.3.0-beta05 https://developer.android.com/jetpack/androidx/releases/compose-material3
compose-compiler = "1.5.14" # https://developer.android.com/jetpack/androidx/releases/compose-compiler
constraintlayout = "2.1.4" # https://developer.android.com/jetpack/androidx/releases/constraintlayout
constraintlayout-compose = "1.0.1" # https://developer.android.com/jetpack/androidx/releases/constraintlayout
coordinatorlayout = "1.2.0" # https://developer.android.com/jetpack/androidx/releases/coordinatorlayout
coroutines = "1.8.0" # https://github.com/Kotlin/kotlinx.coroutines/releases
datastore = "1.1.1" # https://developer.android.com/jetpack/androidx/releases/datastore
firebase-bom = "33.1.2" # https://firebase.google.com/support/release-notes/android#compare-bom-versions
fragment = "1.8.2" # https://developer.android.com/jetpack/androidx/releases/fragment
google-services = "4.4.2" # https://developers.google.com/android/guides/releases
hilt = "2.51.1" # https://github.com/google/dagger/releases
hilt-androidx = "1.2.0" # https://developer.android.com/jetpack/androidx/releases/hilt
junit = "1.2.1" # https://developer.android.com/jetpack/androidx/releases/test
kotlin = "1.9.24" # https://kotlinlang.org/docs/releases.html
kotlinx-serialization = "1.6.3" # https://github.com/Kotlin/kotlinx.serialization/releases
ksp = "1.9.24-1.0.20" # https://github.com/google/ksp/releases
ktlint = "12.1.1" # https://github.com/JLLeitschuh/ktlint-gradle/releases
lifecycle = "2.8.4" # https://developer.android.com/jetpack/androidx/releases/lifecycle
media3 = "1.4.0" # https://developer.android.com/jetpack/androidx/releases/media3
min-sdk = "26" # https://developer.android.com/guide/topics/manifest/uses-sdk-element
navigation = "2.7.7" # https://developer.android.com/jetpack/androidx/releases/navigation
okhttp = "4.12.0" # https://github.com/square/okhttp/blob/master/CHANGELOG.md
oss-licenses-plugin = "0.10.6" # https://github.com/google/play-services-plugins/releases
paging = "3.3.2" # https://developer.android.com/jetpack/androidx/releases/paging
play-core = "1.8.1" # https://developer.android.com/reference/com/google/android/play/core/release-notes
play-services-oss-licenses = "17.1.0" # https://developers.google.com/android/guides/releases
protobuf = "4.27.3" # https://central.sonatype.com/artifact/com.google.protobuf/protobuf-kotlin-lite/versions
protobuf-plugin = "0.9.4" # https://github.com/google/protobuf-gradle-plugin/releases
realm = "1.15.0" # https://github.com/realm/realm-kotlin/blob/main/CHANGELOG.md
recyclerview = "1.3.2" # https://developer.android.com/jetpack/androidx/releases/recyclerview
retrofit = "2.11.0" # https://github.com/square/retrofit/releases/
robolectric = "4.12.2" # https://github.com/robolectric/robolectric/releases
room = "2.6.1" # https://developer.android.com/jetpack/androidx/releases/room
rxandroid = "3.0.2" # https://github.com/ReactiveX/RxAndroid/releases
rxjava = "3.1.8" # https://github.com/ReactiveX/RxJava/releases
test-core-ktx = "1.6.1" # https://developer.android.com/jetpack/androidx/releases/test
test-rules = "1.6.1" # https://developer.android.com/jetpack/androidx/releases/test
test-runner = "1.6.1" # https://developer.android.com/jetpack/androidx/releases/test
viewpager2 = "1.1.0" # https://developer.android.com/jetpack/androidx/releases/viewpager2

[libraries]
activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-plugin" }
animation = { group = "androidx.compose.animation", name = "animation" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout-compose" }
coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinatorlayout" }
datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-config = { group = "com.google.firebase", name = "firebase-config" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
foundation = { group = "androidx.compose.foundation", name = "foundation" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "fragment" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "google-services" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-compiler-androidx = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt-androidx" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-androidx" }
junit = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junit" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
lifecycle-compiler = { group = "androidx.lifecycle", name = "lifecycle-compiler", version.ref = "lifecycle" }
lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }
navigation-safe-args-gradle-plugin = { group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" }
okhttp-urlconnection = { group = "com.squareup.okhttp3", name = "okhttp-urlconnection", version.ref = "okhttp" } # for CookieJar
oss-licenses-plugin = { group = "com.google.android.gms", name = "oss-licenses-plugin", version.ref = "oss-licenses-plugin" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
play-core-ktx = { group = "com.google.android.play", name = "core-ktx", version.ref = "play-core" }
play-services-oss-licenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "play-services-oss-licenses" }
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }
realm = { group = "io.realm.kotlin", name = "library-base", version.ref = "realm" }
realm-gradle-plugin = { group = "io.realm.kotlin", name = "gradle-plugin", version.ref = "realm" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
retrofit-bom = { group = "com.squareup.retrofit2", name = "retrofit-bom", version.ref = "retrofit" }
retrofit-converter-kotlinx-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
rules = { group = "androidx.test", name = "rules", version.ref = "test-rules" }
runner = { group = "androidx.test", name = "runner", version.ref = "test-runner" }
rxandroid = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxandroid" }
rxjava = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava" }
test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "test-core-ktx" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }

[plugins]
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
